name: Tally
options:
  bundleIdPrefix: com.heyitsmejosh
  deploymentTarget:
    iOS: "17.0"
settings:
  SWIFT_VERSION: "6.0"
  MARKETING_VERSION: "1.0.0"
  CURRENT_PROJECT_VERSION: "1"
targets:
  Tally:
    type: application
    platform: iOS
    sources:
      - path: .
        excludes:
          - "*.xcodeproj"
          - "*.yml"
          - ".git"
          - ".gitignore"
          - "README.md"
          - "CLAUDE.md"
          - "architecture.svg"
    settings:
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.heyitsmejosh.tally
